### PR TITLE
Update cask syntax

### PR DESCRIPTION
**Pull request by onurakpolat**
As of 2021 the cask syntax has changed.

### CODE REVIEW

**Comment by JohanAR** [comment]
I don't know Mac ecosystem, but are changes like this pushed to everybody (I mean similar to as if MS makes a change to Windows 10, then it's reasonable to assume that all Windows 10 users will get this update) or will there be some people who have brew with the new syntax, and some who have the old?

**Comment by onurakpolat** [comment]
Its a global change that affects all brew 3.0 users [0]. If you're using an old version of brew, than the old syntax will work.

[0]: https://brew.sh/2021/02/05/homebrew-3.0.0/

**Comment by JohanAR** [comment]
What I'm trying to ask is if we update the doc to the new syntax, will the instructions stop working for everybody who uses the older version? Or is your proposed change compatible with both new and old? If not, I think it might be better to have both commands and tell people to pick the one corresponding to their brew version

**Comment by NinoScript** [comment]
Hello, I was about to write this same change.
Please merge this PR!

As it is right now, it just doesn't work.
image

**Comment by NinoScript** [comment]
> What I'm trying to ask is if we update the doc to the new syntax, will the instructions stop working for everybody who uses the older version? Or is your proposed change compatible with both new and old? If not, I think it might be better to have both commands and tell people to pick the one corresponding to their brew version

Brew updates itself when you use it, so it's hard to have an old version.
In fact this particular breaking change was a bit controversial, because the syntax was deprecated and removed in just a couple of months, breaking many continuous integration setups.

**Comment by JohanAR** [comment]
Thanks!

**Pull request merged**
