### PR TITLE
Ported for Jetson TX2

### PR DESCRIPTION
**Pull request by SVL101**

### CODE REVIEW

**Comment by E3V3A** [comment]
@SVL101  
Huh? What are you actually fixing?
There's a reason why there are (git) commit messages available. Use them!

**Comment by alievk** [comment]
Hi @SVL101 , thank you for this interesting work!

I can't merge this work for several reasons:
1. None of us (maintainers) have Jetson TX2 to test and maintain the code;
2. Your PR has lot's of conflicts with the master branch, like rewriting half of the README and removing our platform scripts.

What we could do:
You can integrate this port into the upstream version and then we will merge this to an experimental branch to allow interested people play with it. Please don't remove scripts or rewrite stuff: create a separate script for your platform and requirements file, like scripts/install_jetson.sh and requirements_jetson.txt. README should be also treated carefully: just add a section for Jetson or a link to a Wiki page (preferred).

If this happens we would also kindly ask you to support people in the issues since we don't have the device on hand.

25FPS is quite impressive, I didn't expect such performance. How did you measure that?

**Comment by SVL101** [comment]
> @SVL101
> Huh? What are you actually fixing?
> There's a reason why there are (git) commit messages available. Use them!

By "fix" I meant small corrections of typos and the like, I thought it would be clear when looking at the code.
I'm sorry, I'm new to Gitgub and I make mistakes in working with him.

**Comment by SVL101** [comment]
> Hi @SVL101 , thank you for this interesting work!
> 
> I can't merge this work for several reasons:
> 
>     1. None of us (maintainers) have Jetson TX2 to test and maintain the code;
> 
>     2. Your PR has lot's of conflicts with the master branch, like rewriting half of the README and removing our platform scripts.
> 
> 
> What we could do:
> You can integrate this port into the upstream version and then we will merge this to an experimental branch to allow interested people play with it. Please don't remove scripts or rewrite stuff: create a separate script for your platform and requirements file, like scripts/install_jetson.sh and requirements_jetson.txt. README should be also treated carefully: just add a section for Jetson or a link to a Wiki page (preferred).
> 
> If this happens we would also kindly ask you to support people in the issues since we don't have the device on hand.
> 
> 25FPS is quite impressive, I didn't expect such performance. How did you measure that?

Thanks for the answer.
The main changes concern the install_jetson.sh, run_jetson.sh files. I haven't been able to run the anaconda on Jetson yet, so I removed the use of the anaconda.
Also because of this, README was changed because Jetson requires a different approach to installation, requires additional dependencies and more.
I have a device now but I can't guarantee long-term support in the future. I may not have a device in the future.
25fps I got by pressing I, I get 22-27 frames on the Jetson TX2
I'm sorry, I'm new to Gitgub and I make mistakes in working with him.
I will try to fix this according to your advice. Have a good day.

**Comment by SVL101** [comment]
Hi @alievk 
I made the necessary changes to resolve conflicts with the main branch.
The changes concern new files for Jetson and some README additions.
Have a good day.

**Comment by alievk** [comment]
Hi @SVL101 ,

Thank you so much for this work.

I've merged your branch into [contrib/jetsontx2](https://github.com/alievk/avatarify/tree/contrib/jetsontx2), resolved some conflicts and moved some files for consistency. Please check this branch if it still works.

There're two reasons I haven't merged this into the master branch.

As I mentioned before, non of us (maintainers) own a Jetson TX2 and we can't maintain the code and support the users. So I would kindly ask you to help people in the issues trying to run the code on Jetson.

The second reason is Jetson, still cool and powerful, is not a very common device. But it's super cool you were able to run it on Jetson!

Thank you for doing this :)

**Comment by SVL101** [comment]
Hi.
I checked the contrib / jetsontx2 branch everything works fine.
Have a good day.

**Pull request closed without merging**
