### PR TITLE
Add overlay drawing of landmarks

### PR DESCRIPTION
**Pull request by JohanAR**
Seeing the landmarks of both the current frame and the avatar can make it easier to get a good pose. I also thought it was interesting to expose a little of the underlying techniques

### CODE REVIEW

**Comment by alievk** [comment]
Hey! I would tune this a little bit more to align with the avatar image on overlay. Misalignment with the overlay looks distracting, 

image

**Comment by JohanAR** [comment]
Did you perhaps run it without video input? There's supposed to be a blue face too from the current frame landmarks. I agree it can be a little distracting, but when I'm using this I pretty much ignore the video in the background and just try to align my landmarks with the avatar's so I can get a good calibration.

I can't really say I understand the mathematics for all this, but I think you get best results if you manage to minimize the difference between your normalized landmarks and the avatar's normalized landmarks, right? So my reasoning was that drawing the  normalized landmarks was more useful, even if drawing pre-normalized landmarks would look better :)

I'll change it to drawing pre-normalized landmarks if you think that is better though. It will require a little bit more code since these values aren't available in the main function now, but it's definitely doable.

I think another option would be to use the same normalization for both faces. E.g. draw the pre-normalized landmarks from the current frame, so that the overlay matches your input video, and then apply the same offsets to the avatar's normalized landmarks. I *think* this would be possible, and my thought was that this might help minimizing the differences..

**Comment by alievk** [comment]
> Did you perhaps run it without video input?

No, I just hid my face to focus on the avatar :) 

> I think you get best results if you manage to minimize the difference between your normalized landmarks and the avatar's normalized landmarks, right?

That totally makes sense!

Let me test it a little bit more before I merge.

**Comment by JohanAR** [comment]
No problem, just let me know if you want me to change anything

**Comment by alievk** [comment]
The entire feature of landmark matching looks promising, but needs more testing to mature.

I played with it once more and to be honest it feels unintuitive when landmarks are detached from my face. Your idea sounds reasonable:
> I think another option would be to use the same normalization for both faces. E.g. draw the pre-normalized landmarks from the current frame, so that the overlay matches your input video, and then apply the same offsets to the avatar's normalized landmarks. I think this would be possible, and my thought was that this might help minimizing the differences..

Can we try?

**Comment by JohanAR** [comment]
Unfortunately I couldn't come up with a good way to overlay the avatar landmarks on current frame's landmarks.. I played around with just drawing non-normalized landmarks, and it does indeed look better (and less confusing), but I really like the information you got from the original 2-normalized-face style..

What would you think about making the first overlay mode draw non-normalized landmarks, which are aligned with current frame and the avatar image, and if you press the button again it switches to draw normalized landmarks? I'm also thinking the normalized view could have the camera image slightly dimmed, to make the overlay stand out more which might reduce the confusion

**Comment by alievk** [comment]
> I'm also thinking the normalized view could have the camera image slightly dimmed, to make the overlay stand out more which might reduce the confusion

This is interesting. Ideally I would make one working-for-all mode, rather than suggesting several variations :)

**Comment by JohanAR** [comment]
For me it would feel pretty natural if one could cycle through different overlays, but maybe they aren't distinctive enough.

I think if you draw the landmarks on top of the faces it could help with "debugging" bad tracking, because it would be easy to see if the landmarks aren't aligned with your face. While using this mode I noticed that it was actually misidentifying my chin.

The other mode, which draws the two normalized landmark sets, helps finding a good pose for calibration and I use it all the time. For me this has completely replaced the overlay, because I think it's easier to line up the contours than the blended images.

But it's your software so you decide what goes in it of course :) I'll try dimming the background tomorrow and see what it feels like.. and I'll include the version with non-normalized overlays so you can try it too if you want

**Comment by JohanAR** [comment]
I pushed a prototype with the latest suggestions, but it uses the PredictorLocal internals from main so it would require some refactoring

**Comment by alievk** [comment]
I totally agree that matching landmarks is much more convenient than matching blended images.

Thinking about it once more, I realized matching non-normalized landmarks would require moving your head to the avatar's head, which is not convenient and does not make much sense, since the neural network's motion detector is (almost) shift-invariant.

Regarding second mode you added (drawing non-normalized landmarks over the user's image), I always try to keep it simple and would refrain from adding it until there is no obvious advantage.

Dimming webcam image works, it actually helps to focus on the landmarks.

**Comment by JohanAR** [comment]
Removed everything except toggle normalized landmarks on/off.. That's how you meant you liked it best, right?

**Comment by alievk** [comment]
Excellent job bro!

One last thing would make it perfect: it's better to switch off the landmarks mode when you calibrate (press X). Imagine this scenario: a user fits landmarks and calibrates. Then she focus on the avatar and wonder why video refresh rate slowed down. Most of the users wouldn't take into account that extra overhead from the landmark detector you and me know about.

**Comment by JohanAR** [comment]
Good idea. I'll try to fix it today and push an updated commit

**Comment by JohanAR** [comment]
So with the risk of drawing this out further :) I added some overlay text while the landmark overlay is visible, because it felt like it was a good idea now that we're integrating it more with the calibration process. I also renamed it to "face detection overlay" in the README, since the word landmark seems to be more of a technical term and it was not mentioned in any other place

**Comment by alievk** [comment]
Excellent work bro, you are amazing!

**Comment by JohanAR** [comment]
Thanks! And thank you for making great open source software!

**Pull request merged**
