### PR TITLE
Exit if either window is closed

### PR DESCRIPTION
**Pull request by JohanAR**

### CODE REVIEW

**Comment by JohanAR** [comment]
I don't know if startWindowThread() is strictly necessary, since it was working before it was added, but if I read the docs right it should be called at some point..

**Comment by alievk** [comment]
I've never used it before, what's the point?

**Comment by JohanAR** [comment]
Well, the OpenCV docs actually doesn't say what it's for.. But I was searching for ways to detect window close button press, and came across several posts saying that at some point during your program you'd have to call startWindowThread for it to process events properly.. *But* now I found another post saying that the function is empty (which I verified by checking their github btw) and another commenter claiming that it is deprecated, though it can't be removed because it would break their API.

So I'll just remove that line from this PR :)

**Comment by alievk** [comment]
Cool, thanks! 👍

**Pull request merged**
